version: "3"

services: 

    sql-server:
        image: marcosbonfante/sgm-sql-server:latest
        container_name: sql-server-sgm
        build: 
            context: ../sql
            dockerfile: ./Dockerfile
        environment:
            SA_PASSWORD: "MeuDB@123"
            ACCEPT_EULA: "Y" 
            
    api-identity:
        image: "marcosbonfante/tcc-api-identity:latest"
        container_name: "marcosbonfante-tcc-api-identity"
        build: 
            context: ../src
            dockerfile: ./Services/SGM.Identity.API/Dockerfile
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+5102
        depends_on:
            - sql-server

    api-cidadao:
        image: "marcosbonfante/tcc-api-cidadao:latest"
        container_name: "marcosbonfante-tcc-api-cidadao"
        build: 
            context: ../src
            dockerfile: ./Services/SGM.Cidadao.API/Dockerfile
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+5202
        depends_on:
            - sql-server

    api-solicitacao:
        image: "marcosbonfante/tcc-api-solicitacao:latest"
        container_name: "marcosbonfante-tcc-api-solicitacao"
        build: 
            context: ../src
            dockerfile: ./Services/SGM.Solicitacao.API/Dockerfile
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+5302
        depends_on:
            - sql-server

    api-ordem-servico:
        image: "marcosbonfante/tcc-api-ordem-servico:latest"
        container_name: "marcosbonfante-tcc-api-ordem-servico"
        build: 
            context: ../src
            dockerfile: ./Services/SGM.OrdemServico.API/Dockerfile
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+5402
        depends_on:
            - sql-server

    web-mvc:
        image: "marcosbonfante/tcc-web-mvc:latest"
        container_name: "marcosbonfante-tcc-web-mvc"
        build: 
            context: ../src
            dockerfile: ./Web/SGM.WebApp.MVC/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5101;http://+5102
        volumes: 
            - dpkeys:/var/data_protection_keys/      
        depends_on:
            - api-identity
            - api-cidadao
            - api-solicitacao
            - api-ordem-servico

    sgm-server:
        image: marcosbonfante/sgm-server:latest
        container_name: sgm-server    
        build: 
            context: ./
            dockerfile: ./nginx/Dockerfile 
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web-mvc            

volumes:
    dpkeys:      
